abstract: Hooks to Catalyst
author: Berik Visschers
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Catalyst-Plugin-Hooks
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.7
version: 0.02
